/* =========================================================
   currencies-data.js — full world currency reference list
   Rates are starting estimates (BDT per 1 unit). Update them
   any time from the Currency Management page — editing a
   rate here never rewrites the exchange rate already stored
   on past payments.
   ========================================================= */

const WORLD_CURRENCIES = [
      { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', rate: 1, lastUpdated: '2026-08-20', status: 'Active', isBase: true },
      { code: 'USD', name: 'US Dollar', symbol: '$', rate: 121.8, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'EUR', name: 'Euro', symbol: '€', rate: 142.5, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'GBP', name: 'British Pound', symbol: '£', rate: 164.2, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', rate: 33.15, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', rate: 32.5, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', rate: 33.5, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', rate: 397.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', rate: 323.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', rate: 316.5, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', rate: 89.2, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rate: 80.5, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', rate: 74.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', rate: 91.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', rate: 27.3, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', rate: 15.6, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rate: 0.82, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', rate: 17.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'KRW', name: 'South Korean Won', symbol: '₩', rate: 0.088, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'INR', name: 'Indian Rupee', symbol: '₹', rate: 1.46, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', rate: 0.44, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', rate: 0.91, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', rate: 0.41, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'THB', name: 'Thai Baht', symbol: '฿', rate: 3.5, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', rate: 0.0049, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', rate: 0.0077, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'PHP', name: 'Philippine Peso', symbol: '₱', rate: 2.15, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', rate: 138.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', rate: 11.6, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', rate: 11.4, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'DKK', name: 'Danish Krone', symbol: 'kr', rate: 19.1, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', rate: 30.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', rate: 5.7, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', rate: 0.34, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'RON', name: 'Romanian Leu', symbol: 'lei', rate: 28.2, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', rate: 72.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', rate: 18.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'RUB', name: 'Russian Ruble', symbol: '₽', rate: 1.35, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'TRY', name: 'Turkish Lira', symbol: '₺', rate: 3.55, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', rate: 2.95, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', rate: 33.4, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'EGP', name: 'Egyptian Pound', symbol: '£', rate: 2.55, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'ZAR', name: 'South African Rand', symbol: 'R', rate: 6.85, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', rate: 0.079, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', rate: 0.94, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', rate: 8.1, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', rate: 12.2, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', rate: 39.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', rate: 0.91, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', rate: 171.8, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', rate: 0.0014, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', rate: 0.093, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', rate: 0.0029, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', rate: 1.72, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', rate: 0.058, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', rate: 0.03, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'LAK', name: 'Lao Kip', symbol: '₭', rate: 0.0056, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', rate: 91.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', rate: 0.036, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', rate: 0.235, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'UZS', name: 'Uzbekistani Som', symbol: 'so\'m', rate: 0.0095, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'GEL', name: 'Georgian Lari', symbol: '₾', rate: 45.2, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'AMD', name: 'Armenian Dram', symbol: '֏', rate: 0.315, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', rate: 71.6, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', rate: 22.4, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MXN', name: 'Mexican Peso', symbol: '$', rate: 6.4, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'ARS', name: 'Argentine Peso', symbol: '$', rate: 0.125, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'CLP', name: 'Chilean Peso', symbol: '$', rate: 0.128, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'COP', name: 'Colombian Peso', symbol: '$', rate: 0.028, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', rate: 32.6, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', rate: 3.05, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', rate: 17.6, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', rate: 0.0165, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'VES', name: 'Venezuelan Bolivar', symbol: 'Bs.S', rate: 3.4, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', rate: 2.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', rate: 0.78, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: 'TT$', rate: 17.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BSD', name: 'Bahamian Dollar', symbol: 'B$', rate: 121.8, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', rate: 60.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', rate: 15.8, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', rate: 4.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'NIO', name: 'Nicaraguan Cordoba', symbol: 'C$', rate: 3.3, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'CRC', name: 'Costa Rican Colon', symbol: '₡', rate: 0.235, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', rate: 121.8, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'CUP', name: 'Cuban Peso', symbol: '$', rate: 5.08, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', rate: 3.85, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', rate: 15.1, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', rate: 1.46, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', rate: 7.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', rate: 55.4, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', rate: 30.2, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'WST', name: 'Samoan Tala', symbol: 'T', rate: 45.6, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', rate: 51.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', rate: 14.6, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', rate: 1.02, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'XPF', name: 'CFP Franc', symbol: '₣', rate: 1.19, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'ISK', name: 'Icelandic Krona', symbol: 'kr', rate: 0.89, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'ALL', name: 'Albanian Lek', symbol: 'L', rate: 1.32, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', rate: 2.32, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин', rate: 1.22, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BAM', name: 'Bosnia-Herzegovina Mark', symbol: 'KM', rate: 72.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', rate: 6.85, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', rate: 41.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', rate: 0.217, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'XOF', name: 'West African CFA Franc', symbol: 'CFA', rate: 0.217, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', rate: 45.1, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', rate: 68.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', rate: 68.0, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', rate: 60.4, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', rate: 3.6, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'GYD', name: 'Guyanese Dollar', symbol: 'G$', rate: 0.58, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', rate: 0.93, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', rate: 0.203, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', rate: 0.98, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', rate: 0.048, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', rate: 0.033, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', rate: 0.087, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', rate: 4.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', rate: 0.07, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', rate: 1.91, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', rate: 0.132, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'BWP', name: 'Botswana Pula', symbol: 'P', rate: 8.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', rate: 6.85, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SZL', name: 'Eswatini Lilangeni', symbol: 'L', rate: 6.85, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', rate: 6.85, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', rate: 2.68, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', rate: 8.9, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', rate: 25.2, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', rate: 0.214, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', rate: 0.093, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', rate: 0.043, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', rate: 1.72, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', rate: 0.0142, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', rate: 5.4, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', rate: 0.63, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', rate: 1.29, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'STN', name: 'Sao Tome & Principe Dobra', symbol: 'Db', rate: 5.5, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', rate: 0.263, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', rate: 0.685, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', rate: 8.1, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', rate: 0.0272, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'KGS', name: 'Kyrgystani Som', symbol: 'с', rate: 1.39, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', rate: 11.1, lastUpdated: '2026-08-20', status: 'Active' },
      { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', rate: 34.8, lastUpdated: '2026-08-20', status: 'Active' }
    ];
